Rails.application.routes.draw do
  root to: 'pages#home'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)

  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)

end
