# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Create Departments
Department.create([ 
  {code: 'AAMW', name: 'Art & Arch of Med. World'},
  {code: 'ACCT', name: 'Accounting'},
  {code: 'AFRC', name: 'Africana Studies'},
  {code: 'AFST', name: 'African Studies Program'},
  {code: 'ALAN', name: 'Asian Languages'},
  {code: 'AMCS', name: 'Applied Math & Computatnl Sci.'},
  {code: 'AMHR', name: 'Amharic'},
  {code: 'ANAT', name: 'Anatomy'},
  {code: 'ANCH', name: 'Ancient History'},
  {code: 'ANEL', name: 'Ancient Near East Languages'},
  {code: 'ANTH', name: 'Anthropology'},
  {code: 'APOP', name: 'Applied Positive Psychology'},
  {code: 'ARAB', name: 'Arabic'},
  {code: 'ARCH', name: 'Architecture'},
  {code: 'ARTH', name: 'Art History'},
  {code: 'ASAM', name: 'Asian American Studies'},
  {code: 'ASLD', name: 'American Sign Language'},
  {code: 'ASTR', name: 'Astronomy'},
  {code: 'BCHE', name: 'Biochemistry (Undergrads)'},
  {code: 'BCS', name: 'Bosnian/Croatian/Serbian'},
  {code: 'BDS', name: 'Behavioral & Decision Sciences'},
  {code: 'BE', name: 'Bioengineering'},
  {code: 'BENF', name: 'Benjamin Franklin Seminars'},
  {code: 'BENG', name: 'Bengali'},
  {code: 'BEPP', name: 'Business Econ & Pub Policy'},
  {code: 'BIBB', name: 'Biological Basis of Behavior'},
  {code: 'BIOE', name: 'Bioethics'},
  {code: 'BIOL', name: 'Biology'},
  {code: 'BIOM', name: 'Biomedical Studies'},
  {code: 'BIOT', name: 'Biotechnology'},
  {code: 'BMB', name: 'Biochemistry & Molecular Biophy'},
  {code: 'BMIN', name: 'Biomedical Informatics'},
  {code: 'BSTA', name: 'Biostatistics'},
  {code: 'CAMB', name: 'Cell and Molecular Biology'},
  {code: 'CBE', name: 'Chemical & Biomolecular Engr'},
  {code: 'CHEM', name: 'Chemistry'},
  {code: 'CHIC', name: 'Chichewa'},
  {code: 'CHIN', name: 'Chinese'},
  {code: 'CIMS', name: 'Cinema and Media Studies'},
  {code: 'CIS', name: 'Computer and Information Sci'},
  {code: 'CIT', name: 'Computer and Information Tech'},
  {code: 'CLCH', name: 'Climate Change'},
  {code: 'CLSC', name: 'Classics'},
  {code: 'CLST', name: 'Classical Studies'},
  {code: 'COGS', name: 'Cognitive Science'},
  {code: 'COML', name: 'Comparative Literature'},
  {code: 'COMM', name: 'Communications'},
  {code: 'CPLN', name: 'City Planning'},
  {code: 'CRIM', name: 'Criminology'},
  {code: 'CRWR', name: 'Creative Writing'},
  {code: 'CZCH', name: 'Czech'},
  {code: 'DADE', name: 'Core Curriculum Basic Science'},
  {code: 'DATA', name: 'Data Analytics'},
  {code: 'DATS', name: 'Data Science'},
  {code: 'DCOH', name: 'Community Oral Health'},
  {code: 'DEMG', name: 'Demography'},
  {code: 'DEND', name: 'Endodontics'},
  {code: 'DENT', name: 'Dental'},
  {code: 'DOMD', name: 'Oral Medicine'},
  {code: 'DORT', name: 'Orthodontics'},
  {code: 'DOSP', name: 'Oral Surgery and Pharmacology'},
  {code: 'DPED', name: 'Pediatric Dentistry'},
  {code: 'DRST', name: 'Restorative Dentistry'},
  {code: 'DSGN', name: 'Design'},
  {code: 'DTCH', name: 'Dutch'},
  {code: 'DYNM', name: 'Organizational Dynamics'},
  {code: 'EALC', name: 'East Asian Languages & Civilztn'},
  {code: 'EAS', name: 'Engineering & Applied Science'},
  {code: 'ECON', name: 'Economics'},
  {code: 'EDUC', name: 'Education'},
  {code: 'ENGL', name: 'English'},
  {code: 'ENGR', name: 'Engineering'},
  {code: 'ENM', name: 'Engineering Mathematics'},
  {code: 'ENMG', name: 'Energy Management & Policy'},
  {code: 'ENVS', name: 'Environmental Studies'},
  {code: 'EPID', name: 'Epidemiology'},
  {code: 'ESE', name: 'Electric & Systems Engineering'},
  {code: 'ETHC', name: 'Ethics'},
  {code: 'FILP', name: 'Filipino'},
  {code: 'FNAR', name: 'Fine Arts'},
  {code: 'FNCE', name: 'Finance'},
  {code: 'FOLK', name: 'Folklore'},
  {code: 'FREN', name: 'French'},
  {code: 'GAFL', name: 'Government Administration'},
  {code: 'GAS', name: 'Graduate Arts & Sciences'},
  {code: 'GCB', name: 'Genomics & Comp. Biology'},
  {code: 'GENC', name: 'Genetic Counseling'},
  {code: 'GEND', name: 'Graduate Endodontics'},
  {code: 'GEOL', name: 'Geology'},
  {code: 'GLBS', name: 'Global Studies'},
  {code: 'GORT', name: 'Graduate Orthodontics'},
  {code: 'GPED', name: 'Graduate Pediatric Program'},
  {code: 'GPRD', name: 'Graduate Periodontics'},
  {code: 'GPRS', name: 'Graduate Prosthodontics'},
  {code: 'GREK', name: 'Greek'},
  {code: 'GRMN', name: 'Germanic Languages'},
  {code: 'GSWS', name: "Gender,Sexuality&Women's Stdys"},
  {code: 'GUJR', name: 'Gujarati'},
  {code: 'HCMG', name: 'Health Care Management'},
  {code: 'HEBR', name: 'Hebrew'},
  {code: 'HIND', name: 'Hindi'},
  {code: 'HIST', name: 'History'},
  {code: 'HPR', name: 'Health Policy Research'},
  {code: 'HSOC', name: 'Health & Societies'},
  {code: 'HSPV', name: 'Historic Preservation'},
  {code: 'HSSC', name: 'History & Sociology of Science'},
  {code: 'HUNG', name: 'Hungarian'},
  {code: 'IGBO', name: 'Igbo'},
  {code: 'IMPA', name: 'International Mpa'},
  {code: 'IMUN', name: 'Immunology'},
  {code: 'INDO', name: 'Indonesian'},
  {code: 'INTL', name: 'International Programs'},
  {code: 'INTR', name: 'International Relations'},
  {code: 'INTS', name: 'International Studies'},
  {code: 'IPD', name: 'Integrated Product Design'},
  {code: 'IRIS', name: 'Irish-Gaelic'},
  {code: 'ITAL', name: 'Italian'},
  {code: 'JPAN', name: 'Japanese'},
  {code: 'JWST', name: 'Jewish Studies Program'},
  {code: 'KAND', name: 'Kannada'},
  {code: 'KORN', name: 'Korean'},
  {code: 'LALS', name: 'Latin American & Latino Studies'},
  {code: 'LARP', name: 'Landscape Arch & Regional Plan'},
  {code: 'LATN', name: 'Latin'},
  {code: 'LAW', name: 'Law'},
  {code: 'LAWM', name: 'Master in Law'},
  {code: 'LEAD', name: 'Leadership and Communication'},
  {code: 'LGIC', name: 'Logic, Information and Comp.'},
  {code: 'LGST', name: 'Legal Studies & Business Ethics'},
  {code: 'LING', name: 'Linguistics'},
  {code: 'LSMP', name: 'Life Sciences Management Prog'},
  {code: 'MALG', name: 'Malagasy'},
  {code: 'MAPP', name: 'Master of Applied Positive Psyc'},
  {code: 'MATH', name: 'Mathematics'},
  {code: 'MCS', name: 'Master of Chemical Sciences'},
  {code: 'MEAM', name: 'Mech Engr and Applied Mech'},
  {code: 'MED', name: 'Medical'},
  {code: 'MGEC', name: 'Management of Economics'},
  {code: 'MGMT', name: 'Management'},
  {code: 'MKTG', name: 'Marketing'},
  {code: 'MLA', name: 'Master of Liberal Arts Program'},
  {code: 'MLYM', name: 'Malayalam'},
  {code: 'MODM', name: 'Modern Middle East Studies'},
  {code: 'MPHY', name: 'Medical Physics'},
  {code: 'MRTI', name: 'Marathi'},
  {code: 'MSCI', name: 'Military Science'},
  {code: 'MSE', name: 'Materials Science and Engineer'},
  {code: 'MSSP', name: 'Social Policy'},
  {code: 'MTHS', name: 'Mathematical Sciences'},
  {code: 'MTR', name: 'Mstr Sci Transltl Research'},
  {code: 'MUSA', name: 'Master of Urban Spatial Analyt'},
  {code: 'MUSC', name: 'Music'},
  {code: 'NANO', name: 'Nanotechnology'},
  {code: 'NELC', name: 'Near Eastern Languages & Civlzt'},
  {code: 'NETS', name: 'Networked and Social Systems'},
  {code: 'NEUR', name: 'Neuroscience'},
  {code: 'NGG', name: 'Neuroscience'},
  {code: 'NPLD', name: 'Nonprofit Leadership'},
  {code: 'NSCI', name: 'Naval Science'},
  {code: 'NURS', name: 'Nursing'},
  {code: 'OIDD', name: 'Operations Info Decisions'},
  {code: 'ORGC', name: 'Organizational Anthropology'},
  {code: 'PASH', name: 'Pashto'},
  {code: 'PERS', name: 'Persian'},
  {code: 'PHIL', name: 'Philosophy'},
  {code: 'PHRM', name: 'Pharmacology'},
  {code: 'PHYL', name: 'Physical and Life Sciences'},
  {code: 'PHYS', name: 'Physics'},
  {code: 'PLSH', name: 'Polish'},
  {code: 'PPE', name: 'Philosophy, Politics, Economics'},
  {code: 'PROW', name: 'Professional Writing'},
  {code: 'PRTG', name: 'Portuguese'},
  {code: 'PSCI', name: 'Political Science'},
  {code: 'PSYC', name: 'Psychology'},
  {code: 'PUBH', name: 'Public Health Studies'},
  {code: 'PUNJ', name: 'Punjabi'},
  {code: 'QUEC', name: 'Quechua'},
  {code: 'REAL', name: 'Real Estate'},
  {code: 'REES', name: 'Russian & East European Studies'},
  {code: 'REG', name: 'Regulation'},
  {code: 'RELC', name: 'Religion and Culture'},
  {code: 'RELS', name: 'Religious Studies'},
  {code: 'ROML', name: 'Romance Languages'},
  {code: 'RUSS', name: 'Russian'},
  {code: 'SARB', name: 'Sudanese Arabic'},
  {code: 'SAST', name: 'South Asia Studies'},
  {code: 'SCMP', name: 'Scientific Computing'},
  {code: 'SKRT', name: 'Sanskrit'},
  {code: 'SOCI', name: 'Sociology'},
  {code: 'SPAN', name: 'Spanish'},
  {code: 'SPRO', name: 'Scientific Process'},
  {code: 'STAT', name: 'Statistics'},
  {code: 'STSC', name: 'Science, Technology & Society'},
  {code: 'SWAH', name: 'Swahili'},
  {code: 'SWED', name: 'Swedish'},
  {code: 'SWRK', name: 'Social Work'},
  {code: 'TAML', name: 'Tamil'},
  {code: 'TELU', name: 'Telugu'},
  {code: 'THAI', name: 'Thai'},
  {code: 'THAR', name: 'Theatre Arts'},
  {code: 'TIBT', name: 'Tibetan'},
  {code: 'TIGR', name: 'Tigrinya'},
  {code: 'TURK', name: 'Turkish'},
  {code: 'TWI', name: 'Twi'},
  {code: 'UKRN', name: 'Ukrainian'},
  {code: 'URBS', name: 'Urban Studies'},
  {code: 'URDU', name: 'Urdu'},
  {code: 'VBMS', name: 'Veterinary & Biomedical Science'},
  {code: 'VCSN', name: 'Clinical Studies - Nbc Elect'},
  {code: 'VCSP', name: 'Clinical Studies - Phila Elect'},
  {code: 'VIET', name: 'Vietnamese'},
  {code: 'VIPR', name: 'Viper'},
  {code: 'VISR', name: 'Vet School Ind Study & Research'},
  {code: 'VLST', name: 'Visual Studies'},
  {code: 'VMED', name: 'Csp/Csn Medicine Courses'},
  {code: 'VPTH', name: 'Pathobiology'},
  {code: 'WH', name: 'Wharton Undergraduate'},
  {code: 'WHCP', name: 'Wharton Communication Pgm'},
  {code: 'WHG', name: 'Wharton Graduate'},
  {code: 'WOLF', name: 'Wolof'},
  {code: 'WRIT', name: 'Writing Program'},
  {code: 'YDSH', name: 'Yiddish'},
  {code: 'YORB', name: 'Yoruba'},
  {code: 'ZULU', name: 'Zulu'}
])